name: Deployment production pipeline
on:
  push:
    branches:
      - main
jobs:
  ci_pipeline:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Build
        run: bun run build
      - name: Discord notification
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_USERNAME: Vercel
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: '[{ "author": {"name": "Github actions"}, "title": "Maru CV", "description": "⚒️  Initializing deployment \n\n🪵  **Logs**\n[Click here](https://github.com/Felipeazs/maru-cv/actions)", "color":  1127128 }]'
      - name: Deploy to Vercel
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      - name: Discord notification
        if: success()
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_USERNAME: Vercel
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: '[{ "author": {"name": "Github actions"}, "title": "Maru CV", "description": "✅ Successfully deployed!\n\n🔗 **Link**\n[Click here](https://maru-cv.vercel.app/)", "color": 2541056 }]'
      - name: Discord notification
        if: failure()
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_USERNAME: Vercel
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: '[{ "author": {"name": "Github actions"}, "title": "Maru CV", "description": "🧨 Deployment has failed!\n\n🪵 **Logs**\n[Click here](https://github.com/Felipeazs/maru-cv/actions)", "color": 14177041 }]'
